theme: jekyll-theme-minimal
<!DOCTYPE html>
<html>
<head>
  <title>Carlos Alvarado - Cybersecurity Portfolio</title>
</head>
<body>
  <h1>Welcome to My Cybersecurity Portfolio</h1>
  <p>Hi, I’m Carlos Alvarado — a cybersecurity student passionate about network security, forensics, and SOC operations.</p>
  <h2>Projects</h2>
  <ul>
    <li>🔒 Windows 11 Hardening Lab</li>
    <li>📡 Network Security with MikroTik & UniFi</li>
    <li>🛡 Python Password Strength Checker</li>
  </ul>
  <h2>Contact</h2>
  <p>LinkedIn: <a href="https://linkedin.com/in/carlos-alvarado-370b39275/">My Profile</a></p>
</body>
</html>
